### ISSUE TITLE
Failing test: Server Mocha Tests.src/dev/__tests__/file·js - dev/File constructor throws if path is not a string

### ISSUE THREAD

**Issue by tylersmalley** [tylersmalley/kibana#4]
A test failed on a tracked branch
```

        Error: expected true to equal false
    at Assertion.assert (node_modules/expect.js/index.js:96:13)
    at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
    at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
    at Context.it (src/dev/__tests__/file.js:31:23)
      
```
First failure: [Jenkins Build](foo.bar)

**Comment by tylersmalley** [comment]
New failure: [Jenkins Build](foo.bar)

**Comment by tylersmalley** [comment]
New failure: [Jenkins Build](foo.bar)

**Comment by tylersmalley** [comment]
New failure: [Jenkins Build](foo.bar)
